# Generated by Django 3.1.4 on 2021-02-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210216_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Corporate Headoffice', 'Corporate Headoffice'), ('Operation Department', 'Operation Department'), ('Work Station', 'Work Station'), ('Marketing Division', 'Marketing Division')], max_length=200, null=True)),
                ('Incident_Department', models.CharField(max_length=200, null=True)),
                ('Incident_Location', models.CharField(max_length=200, null=True)),
                ('initial_severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Fatal', 'Fatal')], max_length=200, null=True)),
                ('Suspected_Cause', models.CharField(max_length=200, null=True)),
                ('Immediate_Action_taken', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
