# Generated by Django 3.1.4 on 2021-02-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Sub_Incidents_types',
            field=models.CharField(choices=[('Environmental Incident', 'Environmental Incident'), ('Injuiry/Illness', 'Injuiry/Illness'), ('Property Damage', 'Property Damage'), ('Vehicle', 'Vehicle')], max_length=200, null=True),
        ),
    ]
