# Generated by Django 3.1.4 on 2021-02-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Incident_Department',
            field=models.TextField(null=True),
        ),
    ]
