# Generated by Django 3.1.4 on 2021-02-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210217_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Immediate_Action_taken',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Incident_Location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Suspected_Cause',
            field=models.TextField(null=True),
        ),
    ]
