# Generated by Django 3.1.4 on 2021-02-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210217_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='customer',
        ),
    ]
