# Generated by Django 3.1.4 on 2021-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210217_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_input',
            field=models.DateField(null=True),
        ),
    ]
