# Generated by Django 3.1.4 on 2021-02-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_report_date_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date_input',
        ),
    ]
